services:

  load_balancer:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./config:/app/config
    entrypoint: ["/app/loadbalancer", "-config", "/app/config/config.example.yaml"]
    restart: unless-stopped
    network_mode: bridge

volumes:
  config:
