load_balancer:
  port: 8080
  strategy: round-robin
  backends:
    - url: http://localhost:8081
      healthcheck:
        interval: 5s
        path: /health
    - url: http://localhost:8082
      healthcheck:
        interval: 5s
        path: /health
    - url: http://localhost:8083
      healthcheck:
        interval: 5s
        path: /health
rate_limiter:
  default_bucket:
    capacity: 10
    refill_rps: 1
db:
  dbms: postgres
  dsn: postgresql://someuser:somepass@localhost:5432/dbname?sslmode=disable
