load_balancer:
  port: 8080
  strategy: round-robin
  backends:
    - url: http://192.168.3.31:8081
      healthcheck:
        interval: 5s
        path: /health
    - url: http://192.168.3.31:8082
      healthcheck:
        interval: 5s
        path: /health
    - url: http://192.168.3.31:8083
      healthcheck:
        interval: 5s
        path: /health
rate_limiter:
  default_bucket:
    capacity: 10
    refill_rps: 1
db:
  dsn: postgresql://someuser:somepass@db:5432/dbname?sslmode=disable
